webtalk_init -webtalk_dir /Volumes/Data/Workspace/ZYNQMP/ultrazed_pciecc_helloA53/helloA53/helloA53.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-11-21 08:02:51" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e6vqqip6o115ij5ujt7km075na" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Gentoo" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Gentoo Base System release 2.6" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2719.934 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.679 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1542751817000" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key isZynqMP -value "true" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key Processors -value "7" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key Arch -value "zynquplus" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key Device -value "xczu3eg" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1542751817000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1542758571632"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1542758571632"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1542758571632"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1542758571632"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1542758571632"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1542758571632"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1542758571632"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1542758571632"
webtalk_transmit -clientid 2461187102 -regid "" -xml /Volumes/Data/Workspace/ZYNQMP/ultrazed_pciecc_helloA53/helloA53/helloA53.sdk/webtalk/usage_statistics_ext_sdk.xml -html /Volumes/Data/Workspace/ZYNQMP/ultrazed_pciecc_helloA53/helloA53/helloA53.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /Volumes/Data/Workspace/ZYNQMP/ultrazed_pciecc_helloA53/helloA53/helloA53.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
